;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				beginning-of-visual-line
				company-complete
				delete-horizontal-space
				end-of-visual-line
				forward-sexp
				haskell-indentation-common-electric-command
				haskell-indentation-newline-and-indent
				helm-M-x
				helm-confirm-and-exit-minibuffer
				hindent-reformat-decl-or-fill
				ignore
				indent-for-tab-command
				kill-region
				kill-visual-line
				kmacro-end-macro
				kmacro-start-macro
				lsp-signature-stop
				ns-copy-including-secondary
				org-cycle
				org-delete-char
				org-end-of-line
				org-force-self-insert
				org-meta-return
				org-return
				org-self-insert-command
				org-todo
				org-yank
				paredit-backslash
				paredit-doublequote
				paredit-forward
				paredit-forward-barf-sexp
				paredit-forward-delete
				paredit-forward-kill-word
				paredit-forward-slurp-sexp
				paredit-kill
				paredit-open-round
				sp-backward-sexp
				sp-forward-barf-sexp
				sp-forward-sexp
				sp-forward-slurp-sexp
				sp-remove-active-pair-overlay
				yaml-electric-backspace
				yaml-electric-dash-and-dot
				))

(setq mc/cmds-to-run-once
      '(
				evil-window-down
				evil-window-right
				handle-switch-frame
				haskell-process-load-file
				iedit-switch-to-mc-mode
				lsp-rename
				lsp-ui-doc--handle-mouse-movement
				mc/mark-all-in-region
				mouse-set-region
				org-ctrl-c-ctrl-c
				set-rectangular-region-anchor
				yas-expand
				))
